___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [2]:
# YOUR CODE IS HERE
import numpy as np  


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [16]:
# YOUR CODE IS HERE
np.arange(5, 26, 5)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [5]:
# YOUR CODE IS HERE
np.zeros(25).reshape(5, 5)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [10]:
# YOUR CODE IS HERE
a = np.ones(16).reshape(4, 4).astype(int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [11]:
# YOUR CODE IS HERE
a + 6


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [13]:
# YOUR CODE IS HERE
np.full((4, 4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [17]:
# YOUR CODE IS HERE
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [18]:
# YOUR CODE IS HERE
np.arange(0, 25).reshape(5, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [23]:
# YOUR CODE IS HERE
np.linspace(0, 24, 25).reshape(5, 5)


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [24]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.24920496, 0.15305317, 0.41256399, 0.2650747 , 0.06915977])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [26]:
# YOUR CODE IS HERE
np.random.randn(25).reshape(5, 5)


array([[-0.71521989,  1.66635651,  0.75820542, -1.06512291, -0.47249053],
       [-1.62322707, -2.28897966,  1.11109453, -0.88363726, -1.31727045],
       [ 0.17773531,  0.94460446,  0.14797617, -1.21701571,  1.57474058],
       [-1.16124571,  0.84968866, -0.75425579, -0.2910282 ,  1.47316165],
       [ 0.63677752,  1.51294888, -1.31456917,  0.48802664,  0.23186632]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [32]:
# YOUR CODE IS HERE
np.random.randint(20, 50, 12).reshape(3, 4)


array([[27, 47, 20, 44],
       [24, 27, 31, 31],
       [49, 23, 42, 25]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [35]:
# YOUR CODE IS HERE
ranarr = np.random.randint(0, 100, 48)
ranarr

array([81, 28, 19, 22, 15, 88, 97, 26, 65, 20, 17, 61, 83, 49, 94, 78, 61,
        5, 97, 12, 14, 70, 53, 44, 28, 80,  8,  3,  9, 15, 84, 86, 77, 73,
       57, 19,  3, 12, 17,  0, 84, 78, 89, 85, 82, 94, 26,  3])

In [36]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
ranarr.reshape(6, 8)


array([[81, 28, 19, 22, 15, 88, 97, 26],
       [65, 20, 17, 61, 83, 49, 94, 78],
       [61,  5, 97, 12, 14, 70, 53, 44],
       [28, 80,  8,  3,  9, 15, 84, 86],
       [77, 73, 57, 19,  3, 12, 17,  0],
       [84, 78, 89, 85, 82, 94, 26,  3]])

In [37]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(6, -1)


array([[81, 28, 19, 22, 15, 88, 97, 26],
       [65, 20, 17, 61, 83, 49, 94, 78],
       [61,  5, 97, 12, 14, 70, 53, 44],
       [28, 80,  8,  3,  9, 15, 84, 86],
       [77, 73, 57, 19,  3, 12, 17,  0],
       [84, 78, 89, 85, 82, 94, 26,  3]])

In [38]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(-1, 8)


array([[81, 28, 19, 22, 15, 88, 97, 26],
       [65, 20, 17, 61, 83, 49, 94, 78],
       [61,  5, 97, 12, 14, 70, 53, 44],
       [28, 80,  8,  3,  9, 15, 84, 86],
       [77, 73, 57, 19,  3, 12, 17,  0],
       [84, 78, 89, 85, 82, 94, 26,  3]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [40]:
# YOUR CODE IS HERE
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [41]:
# YOUR CODE IS HERE 
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [44]:
# YOUR CODE IS HERE 
mat[:4, 0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [45]:
# YOUR CODE IS HERE 
mat[1, 0:4:2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [47]:
# YOUR CODE IS HERE 
mat[:4, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [61]:
# YOUR CODE IS HERE
b = mat[1, 0], mat[3, 2]
np.array(b)

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [71]:
# YOUR CODE IS HERE 
mat[1:4:2, 0:4:2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [72]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [73]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE 
mat[mat < 10]


array([1, 2, 4, 5, 6, 8, 9])

In [74]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat > 12]


array([77, 77, 77, 13, 14, 77, 16])

In [76]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat < 10] + mat[mat > 12]


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [77]:
# YOUR CODE IS HERE 
np.std(mat[mat < 10] + mat[mat > 12])


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [78]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [80]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
# YOUR CODE IS HERE 
mat[:4, 1].sum()


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [85]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
t = mat[:4, 2]
t

array([ 3,  7, 11, 15])

In [97]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 
z = mat[2]
z

array([ 9, 10, 11, 12])

In [104]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
print(np.median(t))
print(np.median(z))

9.0
10.5


In [105]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(t))
print(np.mean(z))

9.0
10.5


In [106]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
print(np.std(t))
print(np.std(z))


4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [36]:
# YOUR CODE IS HERE 
import pandas as pd


### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [37]:
# LET US READ Salaries.csv
sal = pd.read_csv('Salaries (1).csv')
# YOUR CODE IS HERE 


In [119]:
# LET US LOOK AT THE FIRST 5 ROWS
 
# YOUR CODE IS HERE 
sal.head()


Unnamed: 0  Id       EmployeeName  \
0           0   1     NATHANIEL FORD   
1           1   2       GARY JIMENEZ   
2           2   3     ALBERT PARDINI   
3           3   4  CHRISTOPHER CHONG   
4           4   5    PATRICK GARDNER   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0  400184.25       NaN  567595.43         567595.43  2011    NaN   
1  137811.38       NaN  538909.28         538909.28  2011    NaN   
2   16452.60       NaN  335279.91         335279.91  2011    NaN   
3  198306.90       NaN  332343.61         332343.61  2011    NaN   
4  182234.59       NaN  326373.19         326373.19  2011    NaN   

          Agency  Status  
0  San Francisco     NaN  
1  San Francisco     NaN  
2  San Francisco     NaN  
3  San Francisco     NaN  
4  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [121]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 
sal.sample(1)


Unnamed: 0     Id    EmployeeName                JobTitle   BasePay  \
41932       41932  41933  Carlos Soto Jr  Public SafetyComm Disp  82351.58   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
41932     29002.99  13143.79  40667.56  124498.36         165165.92  2012   

       Notes         Agency  Status  
41932    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [123]:
# YOUR CODE IS HERE 
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Unnamed: 0        148654 non-null  int64  
 1   Id                148654 non-null  int64  
 2   EmployeeName      148654 non-null  object 
 3   JobTitle          148654 non-null  object 
 4   BasePay           148045 non-null  float64
 5   OvertimePay       148650 non-null  float64
 6   OtherPay          148650 non-null  float64
 7   Benefits          112491 non-null  float64
 8   TotalPay          148654 non-null  float64
 9   TotalPayBenefits  148654 non-null  float64
 10  Year              148654 non-null  int64  
 11  Notes             0 non-null       float64
 12  Agency            148654 non-null  object 
 13  Status            0 non-null       float64
dtypes: float64(8), int64(3), object(3)
memory usage: 15.9+ MB


In [122]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
sal.describe()


Unnamed: 0             Id        BasePay    OvertimePay  \
count  148654.000000  148654.000000  148045.000000  148650.000000   
mean    74326.500000   74327.500000   66325.448841    5066.059886   
std     42912.857795   42912.857795   42764.635495   11454.380559   
min         0.000000       1.000000    -166.010000      -0.010000   
25%     37163.250000   37164.250000   33588.200000       0.000000   
50%     74326.500000   74327.500000   65007.450000       0.000000   
75%    111489.750000  111490.750000   94691.050000    4658.175000   
max    148653.000000  148654.000000  319275.010000  245131.880000   

            OtherPay       Benefits       TotalPay  TotalPayBenefits  \
count  148650.000000  112491.000000  148654.000000     148654.000000   
mean     3648.767297   25007.893151   74768.321972      93692.554811   
std      8056.601866   15402.215858   50517.005274      62793.533483   
min     -7058.590000     -33.890000    -618.130000       -618.130000   
25%         0.000000   11535.395000   36168.995000      44065.650000   
50%       811.270000   28628.620000   71426.610000      92404.090000   
75%      4236.065000   35566.855000  105839.135000     132876.450000   
max    400184.250000   96570.660000  567595.430000     567595.430000   

                Year  Notes  Status  
count  148654.000000    0.0     0.0  
mean     2012.522643    NaN     NaN  
std         1.117538    NaN     NaN  
min      2011.000000    NaN     NaN  
25%      2012.000000    NaN     NaN  
50%      2013.000000    NaN     NaN  
75%      2014.000000    NaN     NaN  
max      2014.000000    NaN     NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [131]:
# YOUR CODE IS HERE
sal['Year'].value_counts() 


2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [129]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"
sal['Year'].nunique()
# YOUR CODE IS HERE 


4

In [130]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"
sal['Year'].unique()
# YOUR CODE IS HERE 



array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [133]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 

sal['TotalPay'].max()

567595.43

In [135]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 

sal['TotalPay'].mean()

74768.321971703

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [15]:
# YOUR CODE IS HERE 
sal[sal['TotalPay'] > 0] 


Unnamed: 0      Id        EmployeeName  \
0                0       1      NATHANIEL FORD   
1                1       2        GARY JIMENEZ   
2                2       3      ALBERT PARDINI   
3                3       4   CHRISTOPHER CHONG   
4                4       5     PATRICK GARDNER   
...            ...     ...                 ...   
148621      148621  148622      Kenneth Mackey   
148622      148622  148623  Jacqueline Hubbard   
148623      148623  148624     Deborah B Honig   
148624      148624  148625  Lorraine Rosenthal   
148625      148625  148626     Renato C Gurion   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148621                                Transit Operator       0.00   
148622                                    Senior Clerk       0.00   
148623                       Attorney (Civil/Criminal)       0.00   
148624                                    Senior Clerk       0.00   
148625                                Registered Nurse       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148621         0.00      15.35      0.00      15.35             15.35  2014   
148622         0.00      13.77      0.00      13.77             13.77  2014   
148623         0.00      13.35      0.13      13.35             13.48  2014   
148624         0.00      12.89      0.00      12.89             12.89  2014   
148625         0.00       6.00      1.24       6.00              7.24  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148621    NaN  San Francisco     NaN  
148622    NaN  San Francisco     NaN  
148623    NaN  San Francisco     NaN  
148624    NaN  San Francisco     NaN  
148625    NaN  San Francisco     NaN  

[148285 rows x 14 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [12]:
# YOUR CODE IS HERE 
sal.value_counts(sal["TotalPay"] > sal["TotalPay"].mean())


TotalPay
False    79165
True     69489
dtype: int64

### How much does ALBERT PARDINI make money (including benefits)?

In [26]:
# YOUR CODE IS HERE 
sal[sal['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [30]:
# YOUR CODE IS HERE 
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']


148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [31]:
# YOUR CODE IS HERE 
sal['JobTitle'].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [35]:
# YOUR CODE IS HERE 
sal.JobTitle.value_counts(ascending = True).head(3)


LIEUTENANT II (POLICE DEPARTMENT)                     1
ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS    1
BAKER                                                 1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [9]:
# YOUR CODE IS HERE 
sal[(sal['Year'] == 2012) & (sal['TotalPayBenefits'] > sal['TotalPayBenefits'].mean())]['TotalPayBenefits'].count()

20366

### How many people have a title of Manager in their jobs?

In [32]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 
sal[sal.JobTitle.isin(['manager'.upper()])]
sal[sal.JobTitle.apply(lambda x: 'manager'.upper() in x.upper())]["JobTitle"].count()




4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [49]:
# YOUR CODE IS HERE 

sal_new = sal.iloc[:, [1,2,3,8,9]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [51]:
# YOUR CODE IS HERE 

sal_new_df = sal.loc[:, 'EmployeeName' : 'TotalPayBenefits']
sal_new_df

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [59]:
# YOUR CODE IS HERE 
min = sal['TotalPayBenefits'].min()
avg = sal['TotalPayBenefits'].mean()
employee_info = sal[(sal['TotalPayBenefits'] < avg) & (sal['TotalPayBenefits']> min)]
employee_info.iloc[:, [2,9]]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________